name: Scrape and push metrics

on:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  scrape-push:
    name: Scrape and push metrics
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        env:
          PROMETHEUS_REMOTE_WRITE_URL: ${{ vars.PROMETHEUS_REMOTE_WRITE_URL }}
          PROMETHEUS_REMOTE_WRITE_USERNAME: ${{ secrets.PROMETHEUS_REMOTE_WRITE_USERNAME }}
          PROMETHEUS_REMOTE_WRITE_PASSWORD: ${{ secrets.PROMETHEUS_REMOTE_WRITE_PASSWORD }}
          # Using `GH_` prefix due to GitHub Actions restrictions
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          mkdir ./metrics
          docker compose up --quiet-pull --detach --wait

      - name: Download prom-write
        run: |
          curl --location --output /usr/local/bin/prom-write https://github.com/theduke/prom-write/releases/download/v0.2.1/prom-write-linux-x86 \
            && chmod +x /usr/local/bin/prom-write

      # NOTE: Some metrics filtered out including summary metrics, which is not supported by prom-write
      - name: Scrape metrics from GitHub Exporter
        run: |
          curl --silent http://localhost:9171/metrics \
            | grep 'github_' \
            | tee metrics/github-exporter.txt \
            | prom-write --url http://localhost:8080/api/v1/metrics/write --file -

      - name: Scrape metrics from 1Password Exporter
        run: |
          curl --silent http://localhost:9999/metrics \
            | tee metrics/onepassword-exporter.txt \
            | prom-write --url http://localhost:8080/api/v1/metrics/write --file -

      - name: Teardown environment
        env:
          PROMETHEUS_REMOTE_WRITE_URL: ${{ vars.PROMETHEUS_REMOTE_WRITE_URL }}
          PROMETHEUS_REMOTE_WRITE_USERNAME: ${{ secrets.PROMETHEUS_REMOTE_WRITE_USERNAME }}
          PROMETHEUS_REMOTE_WRITE_PASSWORD: ${{ secrets.PROMETHEUS_REMOTE_WRITE_PASSWORD }}
          # Using `GH_` prefix due to GitHub Actions restrictions
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          docker compose stop
          docker compose logs
          docker compose down

      - name: Upload metrics artifact for debugging
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: ./metrics
          if-no-files-found: warn
          retention-days: 3
